### ISSUE TITLE
Add socials of I2IT

### ISSUE THREAD

**Issue by praveenscience** [I2IT-ACM-Student-Chapter/My-Portfolio#7]
It would be nice to connect with I2IT Team. Can someone who knows about their social networks, can you add the links to the readme?

**Comment by RohiniRG** [comment]
I would like to work on this

**Comment by opslash** [comment]
i would

**Comment by rohan-kulkarni-25** [comment]
`[Twitter]()
[LinkedIn]()
[GitHub]()
`

Can copy this and place link in rounded brackets
